### ISSUE TITLE
results in a 500 error

### ISSUE THREAD

**Issue by wolfv** [binder-examples/jupyterlab#2]
Starting up, then get 500 error and something about build instructions in README.md

Maybe delete this, and use the official JupyterLab demo which seems to work?

**Comment by choldgraf** [comment]
good catch! it should be fixed now - the problem was that we were pinning a really old version of the `jupyterlab_launcher` since there was a bug way back when.

I think we should leave the current jupyterlab demo as is, since these binder demos are meant to be short-and-sweet, and the official jupyterlab-demo is way more complex. However, I've linked to it in the readme, because I agree we should be directing people there too.

Can you give this repo another shot and see if it works for you now?

**Comment by wolfv** [comment]
I'm trying but looks like binder is getting hacker-news'd once again :)

**Comment by wolfv** [comment]
Awesome, works! 

And drawio is installed, too! :)

**Comment by choldgraf** [comment]
:-)
